
<table class="table table-striped table-hover">

    <thead>
    <tr>
        <th>Company name</th>
        <th>Contact</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->leads as $lead):?>
    <tr>
        <td><?=$lead->getCompanyName()?></td>
        <td><?=$lead->getContact()->getName()?></td>
        <td><a href="<?=$this->url('root/lead/view', ['leadId' => $lead->getLeadId()])?>">Details</a></td>
    </tr>
<?php endforeach?>
</tbody>

</table>