<div class="list-group col-md-6">
    <div href="#" class="list-group-item">
        <h4 class="list-group-item-heading">Company Name</h4>
        <p class="list-group-item-text"><?=$this->lead->getCompanyName()?></p>
    </div>
</div>

<div class="list-group col-md-6">
    <div href="#" class="list-group-item">
        <h4 class="list-group-item-heading">Contact Name</h4>
        <p class="list-group-item-text"><?=$this->lead->getContact()->getName()?></p>
    </div>
</div>

<h3>Conversations</h3>
<?php $i = 0;?>
<table class="table table-striped table-hover">

    <thead>
    <tr>
        <th>Id</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->lead->getConversations() as $conversation):?>
        <tr>
            <td><?=$i?></td>
            <td><a href="<?=$this->url('root/conversation/reply', ['conversationId' => $conversation])?>">View</a></td>
        </tr>
        <?php $i++;?>
    <?php endforeach?>
    </tbody>

</table>