<table class="table table-striped table-hover">

    <thead>
    <tr>
        <th>Task Type</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->tasks as $task):?>
        <tr>
            <td><?=$task->getDescription()?></td>
            <td>
                <a href="<?=$this->url('root/conversation/reply', ['conversationId' => $task->getConversationId()])?>">
                    Reply
                </a>
            </td>
        </tr>
    <?php endforeach?>
    </tbody>

</table>
